In [6]:
import sys
sys.path.append('..')
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
import pandas as pd

In [7]:
cued = []
free = []
add = '../results/online'
subs = os.listdir(add)

for sub in subs:
    subFolder = add+os.sep+sub
    if os.path.exists(subFolder+os.sep+'cuedPerformance.csv'):

        f = pd.read_csv(subFolder+os.sep+'cuedPerformance.csv')
        cued.append(f)

        f = pd.read_csv(subFolder+os.sep+'freePerformance.csv')
        free.append(f)

cued = pd.concat(cued, ignore_index=True,axis=0)
free = pd.concat(free, ignore_index=True,axis=0)

cued.head()

   Unnamed: 0  accuracy         ITR  winLEN  block    subject
0           0     0.650  253.796926     0.1      0  fanzixiao
1           1     0.775  336.351977     0.1      1  fanzixiao
2           2     0.650  253.796926     0.1      2  fanzixiao
3           3     0.625  238.546826     0.1      3  fanzixiao
4           4     0.825  372.796687     0.1      4  fanzixiao

## Describe Cued spelling

In [3]:
cued.groupby(['subject','winLEN']).describe()[['ITR','accuracy']]

                    ITR                                                 \
                  count        mean        std         min         25%
subject    winLEN
fanzixiao  0.1      5.0  291.057868  59.722182  238.546826  253.796926
           0.2      5.0  426.099248   9.578207  408.965231  430.382752
           0.3      5.0  390.120728  12.356456  376.584908  376.584908
miaoyining 0.1      5.0  145.670938  61.371355   84.454547   95.234860
           0.2      5.0  308.517130  45.962801  244.715703  288.301694
           0.3      5.0  335.261234  31.367877  293.945809  308.826628

                                                      accuracy         \
                          50%         75%         max    count   mean
subject    winLEN
fanzixiao  0.1     253.796926  336.351977  372.796687      5.0  0.705
           0.2     430.382752  430.382752  430.382752      5.0  0.970
           0.3     399.144607  399.144607  399.144607      5.0  0.990
miaoyining 0.1     129.911356  195.072264  223.681661      5.0  0.450
           0.2     303.678819  352.944718  352.944718      5.0  0.805
           0.3     357.844577  357.844577  357.844577      5.0  0.915


                        std    min    25%    50%    75%    max
subject    winLEN
fanzixiao  0.1     0.089093  0.625  0.650  0.650  0.775  0.825
           0.2     0.011180  0.950  0.975  0.975  0.975  0.975
           0.3     0.013693  0.975  0.975  1.000  1.000  1.000
miaoyining 0.1     0.121192  0.325  0.350  0.425  0.550  0.600
           0.2     0.073739  0.700  0.775  0.800  0.875  0.875
           0.3     0.048734  0.850  0.875  0.950  0.950  0.950

## Describe free spelling

In [17]:
sub='miaoyining'
free[(free.subject==sub)&(free.winLEN==0.3)].sort_values(by='ITR',ascending=False)[:5].describe()

       Unnamed: 0  accuracy         ITR  winLEN     block
count    5.000000  5.000000    5.000000     5.0  5.000000
mean    25.200000  0.950000  220.976581     0.3  5.200000
std      2.588436  0.027951   13.780255     0.0  2.588436
min     22.000000  0.937500  214.813864     0.3  2.000000
25%     24.000000  0.937500  214.813864     0.3  4.000000
50%     25.000000  0.937500  214.813864     0.3  5.000000
75%     26.000000  0.937500  214.813864     0.3  6.000000
max     29.000000  1.000000  245.627451     0.3  9.000000

In [19]:
0.95*80

76.0

In [12]:
free.groupby(['subject','winLEN']).describe()[['ITR','accuracy']]

                    ITR                                                 \
                  count        mean        std         min         25%
subject    winLEN
fanzixiao  0.1     10.0  114.619575  58.453163   18.072356   83.201387
           0.2     10.0  196.974994  56.621859   53.205885  187.772464
           0.3     10.0  213.650583  59.805786   49.113125  214.813864
miaoyining 0.1     10.0   59.679751  24.405604   18.072356   46.917889
           0.2     10.0  154.296173  28.679339  119.273413  138.710083
           0.3     10.0  199.311161  30.784896  128.040077  190.047156

                                                      accuracy           \
                          50%         75%         max    count     mean
subject    winLEN
fanzixiao  0.1     130.116451  146.019181  198.256523     10.0  0.55625
           0.2     219.299719  232.715019  232.715019     10.0  0.83750
           0.3     230.220657  245.627451  245.627451     10.0  0.91250
miaoyining 0.1      58.042784   74.192178   91.594199     10.0  0.37500
           0.2     149.087527  176.167602  205.884419     10.0  0.73125
           0.3     202.430510  214.813864  245.627451     10.0  0.89375


                        std     min       25%      50%       75%     max
subject    winLEN
fanzixiao  0.1     0.205079  0.1875  0.468750  0.62500  0.671875  0.8125
           0.2     0.174801  0.3750  0.828125  0.90625  0.937500  0.9375
           0.3     0.191395  0.3750  0.937500  0.96875  1.000000  1.0000
miaoyining 0.1     0.102062  0.1875  0.328125  0.37500  0.437500  0.5000
           0.2     0.083593  0.6250  0.687500  0.71875  0.796875  0.8750
           0.3     0.083593  0.6875  0.875000  0.90625  0.937500  1.0000